name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm audit
      continue-on-error: true

    - run: npm ci

    - run: npm run eslint --if-present

    - run: npm run lint --if-present

    - run: npm run package

    - run: npm run test
      env:
        CI: true
